[context.production]
  command = "yarn build-production"
  publish = ".next"
  [context.production.environment]
    NEXT_PUBLIC_DEPLOY_STAGE='production'

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  YARN_VERSION = "1.22.19"
  NODE_VERSION = "16.13.0" 